[package]
name = "twitch_oauth2_auth_flow"
version = "0.0.1-alpha"
authors = ["stuckoverflow2021"]
edition = "2018"

[dependencies]
futures = "0.3"
log = "0.4"
oauth2 = "4.0.0-alpha"
tiny_http = "0.6"
twitch_api2 = { version = "0.5.0-alpha", features = ["client", "helix", "surf_client", "twitch_oauth2"], git = "https://github.com/Emilgardis/twitch_api2/"  }
twitch_oauth2 = { version = "0.5.0-alpha", features = ["surf_client"], git = "https://github.com/Emilgardis/twitch_oauth2/"  }
url = "2.2"

[dev-dependencies]
surf = "2.2"
tokio = { version = "1", features = ["full"] }
